### ISSUE TITLE
No report in repo

### ISSUE THREAD

**Issue by maherou** [Dbethell001/Bethell-s-Repository#2]
Please provide a report of your findings

**Comment by Dbethell001** [comment]
1. How many darts did you need in a game in order to reliably compute Pi to 3 digits (3.14)?

**ANS:** I needed 18 games and approximately 54 darts in order to reliably compute Pi to 3 digits 

2. What was the standard deviation in this case?

**ANS:** 
Sample of numbers for 18 Games: 3.15, 4, 4, 3.2, 2, 1.4,2,1.4,2.7, 3.0, 3.11, 3.5, 3.25, 3.12, 2.7, 3.11,3.0,3.14

Count: 18
Sum: 51.78
Mean: 2.876666667(Arithmetic mean = Sum / Count)

(Take each number, subtract the mean and square the result)
Differences:
0.2733333333, 1.123333333, 1.123333333, 0.3233333333, -0.8766666667, -1.476666667, -0.8766666667, -1.476666667, -0.1766666667, 0.1233333333, 0.2333333333, 0.6233333333, 0.3733333333, 0.2433333333, -0.1766666667, 0.2333333333, 0.1233333333, 0.2633333333

(Every Number minus Mean)
Differences:
0.07471111109, 1.261877777, 1.261877777, 0.1045444444, 0.7685444445, 2.180544445, 0.7685444445, 2.180544445, 0.03121111112, 0.0152111111, 0.05444444443, 0.3885444444, 0.1393777778, 0.05921111109, 0.03121111112, 0.05444444443, 0.0152111111, 0.06934444443

Sum of Differences: 9.4594 (Add up the Squared Differences)

Variance: 0.5255222222 (Sum of Differences / Count)

Standard Deviation: 0.7249291153 (The square root of the Variance)

**Comment by maherou** [comment]
This is a step in the right direction.  A couple of things to still do:
- You will need a lot more games to obtain an answer that is accurate to three digits.  The results should consistently be 3.14 or better, not just occasionally 3.14.  Also, your standard deviation should be much smaller in that case, with at least two zeros to the right of the decimal place.
- The report should be added as a file to the GitHub repo.  Either a text file or Markdown file would be best.
